# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: full_node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='full_node.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x66ull_node.proto\"\x12\n\x04List\x12\n\n\x02ip\x18\x01 \x03(\t\"?\n\x0cRegistration\x12\x10\n\x08nVersion\x18\x01 \x01(\x05\x12\r\n\x05nTime\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x64\x64rMe\x18\x03 \x01(\t\"P\n\tHandshake\x12\x10\n\x08nVersion\x18\x01 \x01(\x05\x12\r\n\x05nTime\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x64\x64rMe\x18\x03 \x01(\t\x12\x12\n\nbestHeight\x18\x04 \x01(\x05\"\x99\x01\n\x0eNewTransaction\x12\x15\n\rVersionNumber\x18\x01 \x01(\x05\x12\x11\n\tincounter\x18\x02 \x01(\x05\x12\x12\n\noutcounter\x18\x03 \x01(\x05\x12\x16\n\x0elist_of_inputs\x18\x04 \x03(\t\x12\x17\n\x0flist_of_outputs\x18\x05 \x03(\t\x12\x18\n\x10transaction_hash\x18\x06 \x01(\t\"|\n\x06header\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\r\n\x05nonce\x18\x02 \x01(\x03\x12\x17\n\x0fhash_prev_block\x18\x03 \x01(\t\x12\x18\n\x10hash_merkel_root\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x0c\n\x04\x62its\x18\x06 \x01(\x03\"\xb6\x01\n\x08NewBlock\x12\x13\n\x0bMagicNumber\x18\x01 \x01(\x03\x12\x11\n\tBlockSize\x18\x02 \x01(\x03\x12\x1c\n\x0b\x42lockheader\x18\x03 \x01(\x0b\x32\x07.header\x12\x1b\n\x13transaction_counter\x18\x04 \x01(\x03\x12$\n\x0btransaction\x18\x05 \x03(\x0b\x32\x0f.NewTransaction\x12\x11\n\tblockhash\x18\x06 \x01(\t\x12\x0e\n\x06maxtxn\x18\x07 \x01(\x03\"\x07\n\x05\x45mpty2\xb3\x01\n\x0c\x43ommunicator\x12#\n\tRegistrar\x12\r.Registration\x1a\x05.List\"\x00\x12 \n\thandshake\x12\n.Handshake\x1a\x05.List\"\x00\x12\x33\n\x16NewTransactionReceived\x12\x0f.NewTransaction\x1a\x06.Empty\"\x00\x12\'\n\x10NewBlockReceived\x12\t.NewBlock\x1a\x06.Empty\"\x00\x62\x06proto3')
)




_LIST = _descriptor.Descriptor(
  name='List',
  full_name='List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='List.ip', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=37,
)


_REGISTRATION = _descriptor.Descriptor(
  name='Registration',
  full_name='Registration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nVersion', full_name='Registration.nVersion', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nTime', full_name='Registration.nTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addrMe', full_name='Registration.addrMe', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=102,
)


_HANDSHAKE = _descriptor.Descriptor(
  name='Handshake',
  full_name='Handshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nVersion', full_name='Handshake.nVersion', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nTime', full_name='Handshake.nTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addrMe', full_name='Handshake.addrMe', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bestHeight', full_name='Handshake.bestHeight', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=184,
)


_NEWTRANSACTION = _descriptor.Descriptor(
  name='NewTransaction',
  full_name='NewTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VersionNumber', full_name='NewTransaction.VersionNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='incounter', full_name='NewTransaction.incounter', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outcounter', full_name='NewTransaction.outcounter', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_of_inputs', full_name='NewTransaction.list_of_inputs', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_of_outputs', full_name='NewTransaction.list_of_outputs', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_hash', full_name='NewTransaction.transaction_hash', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=340,
)


_HEADER = _descriptor.Descriptor(
  name='header',
  full_name='header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='header.version', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='header.nonce', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_prev_block', full_name='header.hash_prev_block', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_merkel_root', full_name='header.hash_merkel_root', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='header.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bits', full_name='header.bits', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=466,
)


_NEWBLOCK = _descriptor.Descriptor(
  name='NewBlock',
  full_name='NewBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MagicNumber', full_name='NewBlock.MagicNumber', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BlockSize', full_name='NewBlock.BlockSize', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Blockheader', full_name='NewBlock.Blockheader', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_counter', full_name='NewBlock.transaction_counter', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='NewBlock.transaction', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blockhash', full_name='NewBlock.blockhash', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxtxn', full_name='NewBlock.maxtxn', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=651,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=660,
)

_NEWBLOCK.fields_by_name['Blockheader'].message_type = _HEADER
_NEWBLOCK.fields_by_name['transaction'].message_type = _NEWTRANSACTION
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['Registration'] = _REGISTRATION
DESCRIPTOR.message_types_by_name['Handshake'] = _HANDSHAKE
DESCRIPTOR.message_types_by_name['NewTransaction'] = _NEWTRANSACTION
DESCRIPTOR.message_types_by_name['header'] = _HEADER
DESCRIPTOR.message_types_by_name['NewBlock'] = _NEWBLOCK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), dict(
  DESCRIPTOR = _LIST,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:List)
  ))
_sym_db.RegisterMessage(List)

Registration = _reflection.GeneratedProtocolMessageType('Registration', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATION,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:Registration)
  ))
_sym_db.RegisterMessage(Registration)

Handshake = _reflection.GeneratedProtocolMessageType('Handshake', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKE,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:Handshake)
  ))
_sym_db.RegisterMessage(Handshake)

NewTransaction = _reflection.GeneratedProtocolMessageType('NewTransaction', (_message.Message,), dict(
  DESCRIPTOR = _NEWTRANSACTION,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:NewTransaction)
  ))
_sym_db.RegisterMessage(NewTransaction)

header = _reflection.GeneratedProtocolMessageType('header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:header)
  ))
_sym_db.RegisterMessage(header)

NewBlock = _reflection.GeneratedProtocolMessageType('NewBlock', (_message.Message,), dict(
  DESCRIPTOR = _NEWBLOCK,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:NewBlock)
  ))
_sym_db.RegisterMessage(NewBlock)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'full_node_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_COMMUNICATOR = _descriptor.ServiceDescriptor(
  name='Communicator',
  full_name='Communicator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=663,
  serialized_end=842,
  methods=[
  _descriptor.MethodDescriptor(
    name='Registrar',
    full_name='Communicator.Registrar',
    index=0,
    containing_service=None,
    input_type=_REGISTRATION,
    output_type=_LIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='handshake',
    full_name='Communicator.handshake',
    index=1,
    containing_service=None,
    input_type=_HANDSHAKE,
    output_type=_LIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NewTransactionReceived',
    full_name='Communicator.NewTransactionReceived',
    index=2,
    containing_service=None,
    input_type=_NEWTRANSACTION,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NewBlockReceived',
    full_name='Communicator.NewBlockReceived',
    index=3,
    containing_service=None,
    input_type=_NEWBLOCK,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMUNICATOR)

DESCRIPTOR.services_by_name['Communicator'] = _COMMUNICATOR

# @@protoc_insertion_point(module_scope)
